// <auto-generated />
using System;
using Jasarsoft.AmadeusDev.Repo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmadeusDev.Repo.Migrations
{
    [DbContext(typeof(AmadeusDevContext))]
    [Migration("20190623132213_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.AircraftEquipment", b =>
                {
                    b.Property<int>("AircraftEquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.HasKey("AircraftEquipmentId");

                    b.ToTable("AircraftEquipments");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Defaults", b =>
                {
                    b.Property<int>("DefaultId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Adults");

                    b.Property<bool?>("NonStop");

                    b.HasKey("DefaultId");

                    b.ToTable("Defaults");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Dictionaries", b =>
                {
                    b.Property<int>("DictionaryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AircraftId");

                    b.Property<int?>("CarriersId");

                    b.Property<int?>("CurrenciesId");

                    b.Property<int?>("LocationsId");

                    b.HasKey("DictionaryId");

                    b.HasIndex("AircraftId");

                    b.HasIndex("CarriersId");

                    b.HasIndex("CurrenciesId");

                    b.HasIndex("LocationsId");

                    b.ToTable("Dictionaries");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.DictionaryEntry", b =>
                {
                    b.Property<int>("DictionaryEntryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired();

                    b.HasKey("DictionaryEntryId");

                    b.ToTable("DictionaryEntries");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.FlightEndPoint", b =>
                {
                    b.Property<int>("FlightEndPointId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("At");

                    b.Property<string>("IataCode");

                    b.Property<string>("Terminal");

                    b.HasKey("FlightEndPointId");

                    b.ToTable("FlightEndPoints");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.FlightOffer", b =>
                {
                    b.Property<int>("FlightOfferId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FlightOffersFlightOfferid");

                    b.Property<string>("Id");

                    b.Property<string>("Type");

                    b.HasKey("FlightOfferId");

                    b.HasIndex("FlightOffersFlightOfferid");

                    b.ToTable("FlightOffer");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.FlightOffers", b =>
                {
                    b.Property<int>("FlightOfferid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DictionariesId");

                    b.Property<int?>("MetaId");

                    b.HasKey("FlightOfferid");

                    b.HasIndex("DictionariesId");

                    b.HasIndex("MetaId");

                    b.ToTable("FlightOffers");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.FlightSegment", b =>
                {
                    b.Property<int>("FlightSegmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AircraftId");

                    b.Property<int?>("ArrivalId");

                    b.Property<string>("CarrierCode");

                    b.Property<int?>("DepartureId");

                    b.Property<string>("Duration");

                    b.Property<string>("Number");

                    b.Property<int?>("OperatingId");

                    b.HasKey("FlightSegmentId");

                    b.HasIndex("AircraftId");

                    b.HasIndex("ArrivalId");

                    b.HasIndex("DepartureId");

                    b.HasIndex("OperatingId");

                    b.ToTable("FlightSegments");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.FlightStop", b =>
                {
                    b.Property<int>("FlightStopId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArrivalAt");

                    b.Property<string>("DepartureAt");

                    b.Property<string>("Duration");

                    b.Property<int?>("FlightSegmentId");

                    b.Property<string>("IataCode");

                    b.Property<int?>("NewAircraftId");

                    b.HasKey("FlightStopId");

                    b.HasIndex("FlightSegmentId");

                    b.HasIndex("NewAircraftId");

                    b.ToTable("FlightStops");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Issue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Code");

                    b.Property<string>("Detail");

                    b.Property<int?>("FlightOffersFlightOfferid");

                    b.Property<int?>("SourceId");

                    b.Property<int?>("Status");

                    b.Property<string>("Title");

                    b.HasKey("IssueId");

                    b.HasIndex("FlightOffersFlightOfferid");

                    b.HasIndex("SourceId");

                    b.ToTable("Issues");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.IssueSource", b =>
                {
                    b.Property<int>("IssueSourceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Example");

                    b.Property<string>("Parameter");

                    b.Property<string>("Pointer");

                    b.HasKey("IssueSourceId");

                    b.ToTable("Issue_Sources");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Links", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Self");

                    b.HasKey("LinkId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.LocationEntry", b =>
                {
                    b.Property<int>("LocationEntryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .IsRequired();

                    b.HasKey("LocationEntryId");

                    b.ToTable("LocationEntries");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Meta", b =>
                {
                    b.Property<int>("MetaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Currency");

                    b.Property<int?>("DefaultsId");

                    b.Property<int?>("LinksId");

                    b.HasKey("MetaId");

                    b.HasIndex("DefaultsId");

                    b.HasIndex("LinksId");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.OfferItem", b =>
                {
                    b.Property<int>("OfferItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FlightOfferId");

                    b.Property<int?>("PriceId");

                    b.Property<int?>("PricePerAdultId");

                    b.Property<int?>("PricePerChildId");

                    b.Property<int?>("PricePerInfantId");

                    b.Property<int?>("PricePerSeniorId");

                    b.HasKey("OfferItemId");

                    b.HasIndex("FlightOfferId");

                    b.HasIndex("PriceId");

                    b.HasIndex("PricePerAdultId");

                    b.HasIndex("PricePerChildId");

                    b.HasIndex("PricePerInfantId");

                    b.HasIndex("PricePerSeniorId");

                    b.ToTable("OfferItems");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.OperatingFlight", b =>
                {
                    b.Property<int>("OperatingFlightId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarrierCode");

                    b.Property<string>("Number");

                    b.HasKey("OperatingFlightId");

                    b.ToTable("OperatingFlights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Total");

                    b.Property<string>("TotalTaxes");

                    b.HasKey("PriceId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.PricingDetail", b =>
                {
                    b.Property<int>("PricingDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Availability");

                    b.Property<string>("FareBasis");

                    b.Property<string>("FareClass");

                    b.Property<string>("TravelClass");

                    b.HasKey("PricingDetailId");

                    b.ToTable("PricingDetails");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Segment", b =>
                {
                    b.Property<int>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FlightSegmentId");

                    b.Property<int?>("PricingDetailPerAdultId");

                    b.Property<int?>("PricingDetailPerChildId");

                    b.Property<int?>("PricingDetailPerInfantId");

                    b.Property<int?>("PricingDetailPerSeniorId");

                    b.Property<int?>("ServiceId");

                    b.HasKey("SegmentId");

                    b.HasIndex("FlightSegmentId");

                    b.HasIndex("PricingDetailPerAdultId");

                    b.HasIndex("PricingDetailPerChildId");

                    b.HasIndex("PricingDetailPerInfantId");

                    b.HasIndex("PricingDetailPerSeniorId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OfferItemId");

                    b.HasKey("ServiceId");

                    b.HasIndex("OfferItemId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Dictionaries", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.DictionaryEntry", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.DictionaryEntry", "Carriers")
                        .WithMany()
                        .HasForeignKey("CarriersId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.DictionaryEntry", "Currencies")
                        .WithMany()
                        .HasForeignKey("CurrenciesId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.LocationEntry", "Locations")
                        .WithMany()
                        .HasForeignKey("LocationsId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.FlightOffer", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.FlightOffers")
                        .WithMany("Data")
                        .HasForeignKey("FlightOffersFlightOfferid");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.FlightOffers", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.Dictionaries", "Dictionaries")
                        .WithMany()
                        .HasForeignKey("DictionariesId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.Meta", "Meta")
                        .WithMany()
                        .HasForeignKey("MetaId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.FlightSegment", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.AircraftEquipment", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.FlightEndPoint", "Arrival")
                        .WithMany()
                        .HasForeignKey("ArrivalId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.FlightEndPoint", "Departure")
                        .WithMany()
                        .HasForeignKey("DepartureId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.OperatingFlight", "Operating")
                        .WithMany()
                        .HasForeignKey("OperatingId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.FlightStop", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.FlightSegment")
                        .WithMany("Stops")
                        .HasForeignKey("FlightSegmentId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.AircraftEquipment", "NewAircraft")
                        .WithMany()
                        .HasForeignKey("NewAircraftId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Issue", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.FlightOffers")
                        .WithMany("Warnings")
                        .HasForeignKey("FlightOffersFlightOfferid");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.IssueSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Meta", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.Defaults", "Defaults")
                        .WithMany()
                        .HasForeignKey("DefaultsId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.Links", "Links")
                        .WithMany()
                        .HasForeignKey("LinksId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.OfferItem", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.FlightOffer")
                        .WithMany("OfferItems")
                        .HasForeignKey("FlightOfferId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.Price", "PricePerAdult")
                        .WithMany()
                        .HasForeignKey("PricePerAdultId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.Price", "PricePerChild")
                        .WithMany()
                        .HasForeignKey("PricePerChildId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.Price", "PricePerInfant")
                        .WithMany()
                        .HasForeignKey("PricePerInfantId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.Price", "PricePerSenior")
                        .WithMany()
                        .HasForeignKey("PricePerSeniorId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Segment", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.FlightSegment", "FlightSegment")
                        .WithMany()
                        .HasForeignKey("FlightSegmentId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.PricingDetail", "PricingDetailPerAdult")
                        .WithMany()
                        .HasForeignKey("PricingDetailPerAdultId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.PricingDetail", "PricingDetailPerChild")
                        .WithMany()
                        .HasForeignKey("PricingDetailPerChildId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.PricingDetail", "PricingDetailPerInfant")
                        .WithMany()
                        .HasForeignKey("PricingDetailPerInfantId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.PricingDetail", "PricingDetailPerSenior")
                        .WithMany()
                        .HasForeignKey("PricingDetailPerSeniorId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.Service")
                        .WithMany("Segments")
                        .HasForeignKey("ServiceId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Entities.Service", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Entities.OfferItem")
                        .WithMany("Services")
                        .HasForeignKey("OfferItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
