// <auto-generated />
using System;
using Jasarsoft.AmadeusDev.Repo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmadeusDev.Repo.Migrations
{
    [DbContext(typeof(AmadeusDevContext))]
    partial class AmadeusDevContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.Address", b =>
                {
                    b.Property<int>("AdressId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityCode");

                    b.Property<string>("CityName");

                    b.Property<string>("CountryCode");

                    b.Property<string>("CountryName");

                    b.Property<string>("RegionCode");

                    b.Property<string>("StateCode");

                    b.HasKey("AdressId");

                    b.ToTable("Address","Airports");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.Analytics", b =>
                {
                    b.Property<int>("AnalyticsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TravelersId");

                    b.HasKey("AnalyticsId");

                    b.HasIndex("TravelersId");

                    b.ToTable("Analytics","Airports");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.CollectionLinks", b =>
                {
                    b.Property<int>("LinksId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("First");

                    b.Property<string>("Last");

                    b.Property<string>("Next");

                    b.Property<string>("Previous");

                    b.Property<string>("Self");

                    b.Property<string>("Up");

                    b.HasKey("LinksId");

                    b.ToTable("CollectionLinks","Airports");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.CollectionMeta", b =>
                {
                    b.Property<int>("MetaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int?>("LinksId");

                    b.HasKey("MetaId");

                    b.HasIndex("LinksId");

                    b.ToTable("CollectionMeta","Airports");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.Distance", b =>
                {
                    b.Property<int>("DistanceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Unit");

                    b.Property<int?>("Value");

                    b.HasKey("DistanceId");

                    b.ToTable("Distance","Airports");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.GeoCode", b =>
                {
                    b.Property<int>("GeoCodeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GeoCodeId");

                    b.ToTable("GeoCode","Airports");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<int?>("AnalyticsId");

                    b.Property<string>("DetailedName");

                    b.Property<int?>("DistanceId");

                    b.Property<int?>("GeoCodeId");

                    b.Property<string>("IataCode");

                    b.Property<string>("Id");

                    b.Property<string>("Name");

                    b.Property<decimal?>("Relevance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SelfId");

                    b.Property<string>("SubType");

                    b.Property<int>("SuccessId");

                    b.Property<string>("TimeZoneOffset");

                    b.Property<string>("Type");

                    b.HasKey("LocationId");

                    b.HasIndex("AddressId");

                    b.HasIndex("AnalyticsId");

                    b.HasIndex("DistanceId");

                    b.HasIndex("GeoCodeId");

                    b.HasIndex("SelfId");

                    b.HasIndex("SuccessId");

                    b.ToTable("Location","Airports");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.Self", b =>
                {
                    b.Property<int>("SelfId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Href");

                    b.Property<string>("Methods");

                    b.HasKey("SelfId");

                    b.ToTable("Self","Airports");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.Success", b =>
                {
                    b.Property<int>("SuccessId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MetaId");

                    b.HasKey("SuccessId");

                    b.HasIndex("MetaId");

                    b.ToTable("Success","Airports");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.Travelers", b =>
                {
                    b.Property<int>("TravelersId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TravelersId");

                    b.ToTable("Travelers","Airports");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.AircraftEquipment", b =>
                {
                    b.Property<int>("AircraftEquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.HasKey("AircraftEquipmentId");

                    b.ToTable("AircraftEquipment","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Defaults", b =>
                {
                    b.Property<int>("DefaultId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Adults");

                    b.Property<bool?>("NonStop");

                    b.HasKey("DefaultId");

                    b.ToTable("Defaults","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Dictionaries", b =>
                {
                    b.Property<int>("DictionaryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AircraftId");

                    b.Property<int?>("CarriersId");

                    b.Property<int?>("CurrenciesId");

                    b.Property<int?>("LocationsId");

                    b.HasKey("DictionaryId");

                    b.HasIndex("AircraftId");

                    b.HasIndex("CarriersId");

                    b.HasIndex("CurrenciesId");

                    b.HasIndex("LocationsId");

                    b.ToTable("Dictionaries","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.DictionaryEntry", b =>
                {
                    b.Property<int>("DictionaryEntryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.HasKey("DictionaryEntryId");

                    b.ToTable("DictionaryEntry","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.FlightEndPoint", b =>
                {
                    b.Property<int>("FlightEndPointId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("At");

                    b.Property<string>("IataCode");

                    b.Property<string>("Terminal");

                    b.HasKey("FlightEndPointId");

                    b.ToTable("FlightEndPoint","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.FlightOffer", b =>
                {
                    b.Property<int>("FlightOfferId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FlightOffersId");

                    b.Property<string>("Id");

                    b.Property<string>("Type");

                    b.HasKey("FlightOfferId");

                    b.HasIndex("FlightOffersId");

                    b.ToTable("FlightOffer","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.FlightOffers", b =>
                {
                    b.Property<int>("FlightOffersId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DictionariesId");

                    b.Property<int?>("MetaId");

                    b.HasKey("FlightOffersId");

                    b.HasIndex("DictionariesId");

                    b.HasIndex("MetaId");

                    b.ToTable("FlightOffers","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.FlightSegment", b =>
                {
                    b.Property<int>("FlightSegmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AircraftId");

                    b.Property<int?>("ArrivalId");

                    b.Property<string>("CarrierCode");

                    b.Property<int?>("DepartureId");

                    b.Property<string>("Duration");

                    b.Property<string>("Number");

                    b.Property<int?>("OperatingId");

                    b.HasKey("FlightSegmentId");

                    b.HasIndex("AircraftId");

                    b.HasIndex("ArrivalId");

                    b.HasIndex("DepartureId");

                    b.HasIndex("OperatingId");

                    b.ToTable("FlightSegment","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.FlightStop", b =>
                {
                    b.Property<int>("FlightStopId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArrivalAt");

                    b.Property<string>("DepartureAt");

                    b.Property<string>("Duration");

                    b.Property<int?>("FlightSegmentId");

                    b.Property<string>("IataCode");

                    b.Property<int?>("NewAircraftId");

                    b.HasKey("FlightStopId");

                    b.HasIndex("FlightSegmentId");

                    b.HasIndex("NewAircraftId");

                    b.ToTable("FlightStop","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Issue", b =>
                {
                    b.Property<int>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Code");

                    b.Property<string>("Detail");

                    b.Property<int?>("FlightOffersId");

                    b.Property<int?>("SourceId");

                    b.Property<int?>("Status");

                    b.Property<string>("Title");

                    b.HasKey("IssueId");

                    b.HasIndex("FlightOffersId");

                    b.HasIndex("SourceId");

                    b.ToTable("Issue","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.IssueSource", b =>
                {
                    b.Property<int>("IssueSourceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Example");

                    b.Property<string>("Parameter");

                    b.Property<string>("Pointer");

                    b.HasKey("IssueSourceId");

                    b.ToTable("IssueSource","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Links", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Self");

                    b.HasKey("LinkId");

                    b.ToTable("Links","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.LocationEntry", b =>
                {
                    b.Property<int>("LocationEntryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key");

                    b.HasKey("LocationEntryId");

                    b.ToTable("LocationEntry","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Meta", b =>
                {
                    b.Property<int>("MetaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Currency");

                    b.Property<int?>("DefaultsId");

                    b.Property<int?>("LinksId");

                    b.HasKey("MetaId");

                    b.HasIndex("DefaultsId");

                    b.HasIndex("LinksId");

                    b.ToTable("Meta","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.OfferItem", b =>
                {
                    b.Property<int>("OfferItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FlightOfferId");

                    b.Property<int?>("PriceId");

                    b.Property<int?>("PricePerAdultId");

                    b.Property<int?>("PricePerChildId");

                    b.Property<int?>("PricePerInfantId");

                    b.Property<int?>("PricePerSeniorId");

                    b.HasKey("OfferItemId");

                    b.HasIndex("FlightOfferId");

                    b.HasIndex("PriceId");

                    b.HasIndex("PricePerAdultId");

                    b.HasIndex("PricePerChildId");

                    b.HasIndex("PricePerInfantId");

                    b.HasIndex("PricePerSeniorId");

                    b.ToTable("OfferItem","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.OperatingFlight", b =>
                {
                    b.Property<int>("OperatingFlightId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarrierCode");

                    b.Property<string>("Number");

                    b.HasKey("OperatingFlightId");

                    b.ToTable("OperatingFlight","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Total");

                    b.Property<string>("TotalTaxes");

                    b.HasKey("PriceId");

                    b.ToTable("Price","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.PricingDetail", b =>
                {
                    b.Property<int>("PricingDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Availability");

                    b.Property<string>("FareBasis");

                    b.Property<string>("FareClass");

                    b.Property<string>("TravelClass");

                    b.HasKey("PricingDetailId");

                    b.ToTable("PricingDetail","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Segment", b =>
                {
                    b.Property<int>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FlightSegmentId");

                    b.Property<int?>("PricingDetailPerAdultId");

                    b.Property<int?>("PricingDetailPerChildId");

                    b.Property<int?>("PricingDetailPerInfantId");

                    b.Property<int?>("PricingDetailPerSeniorId");

                    b.Property<int?>("ServiceId");

                    b.HasKey("SegmentId");

                    b.HasIndex("FlightSegmentId");

                    b.HasIndex("PricingDetailPerAdultId");

                    b.HasIndex("PricingDetailPerChildId");

                    b.HasIndex("PricingDetailPerInfantId");

                    b.HasIndex("PricingDetailPerSeniorId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Segment","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OfferItemId");

                    b.HasKey("ServiceId");

                    b.HasIndex("OfferItemId");

                    b.ToTable("Service","Flights");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.Analytics", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Airports.Travelers", "Travelers")
                        .WithMany()
                        .HasForeignKey("TravelersId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.CollectionMeta", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Airports.CollectionLinks", "Links")
                        .WithMany()
                        .HasForeignKey("LinksId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.Location", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Airports.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Airports.Analytics", "Analytics")
                        .WithMany()
                        .HasForeignKey("AnalyticsId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Airports.Distance", "Distance")
                        .WithMany()
                        .HasForeignKey("DistanceId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Airports.GeoCode", "GeoCode")
                        .WithMany()
                        .HasForeignKey("GeoCodeId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Airports.Self", "Self")
                        .WithMany()
                        .HasForeignKey("SelfId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Airports.Success", "Success")
                        .WithMany("Data")
                        .HasForeignKey("SuccessId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Airports.Success", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Airports.CollectionMeta", "Meta")
                        .WithMany()
                        .HasForeignKey("MetaId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Dictionaries", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.DictionaryEntry", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.DictionaryEntry", "Carriers")
                        .WithMany()
                        .HasForeignKey("CarriersId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.DictionaryEntry", "Currencies")
                        .WithMany()
                        .HasForeignKey("CurrenciesId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.LocationEntry", "Locations")
                        .WithMany()
                        .HasForeignKey("LocationsId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.FlightOffer", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.FlightOffers", "FlightOffers")
                        .WithMany("Data")
                        .HasForeignKey("FlightOffersId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.FlightOffers", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.Dictionaries", "Dictionaries")
                        .WithMany()
                        .HasForeignKey("DictionariesId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.Meta", "Meta")
                        .WithMany()
                        .HasForeignKey("MetaId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.FlightSegment", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.AircraftEquipment", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.FlightEndPoint", "Arrival")
                        .WithMany()
                        .HasForeignKey("ArrivalId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.FlightEndPoint", "Departure")
                        .WithMany()
                        .HasForeignKey("DepartureId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.OperatingFlight", "Operating")
                        .WithMany()
                        .HasForeignKey("OperatingId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.FlightStop", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.FlightSegment", "FlightSegment")
                        .WithMany("Stops")
                        .HasForeignKey("FlightSegmentId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.AircraftEquipment", "NewAircraft")
                        .WithMany()
                        .HasForeignKey("NewAircraftId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Issue", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.FlightOffers", "FlightOffers")
                        .WithMany("Warnings")
                        .HasForeignKey("FlightOffersId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.IssueSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Meta", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.Defaults", "Defaults")
                        .WithMany()
                        .HasForeignKey("DefaultsId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.Links", "Links")
                        .WithMany()
                        .HasForeignKey("LinksId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.OfferItem", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.FlightOffer", "FlightOffer")
                        .WithMany("OfferItems")
                        .HasForeignKey("FlightOfferId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.Price", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.Price", "PricePerAdult")
                        .WithMany()
                        .HasForeignKey("PricePerAdultId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.Price", "PricePerChild")
                        .WithMany()
                        .HasForeignKey("PricePerChildId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.Price", "PricePerInfant")
                        .WithMany()
                        .HasForeignKey("PricePerInfantId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.Price", "PricePerSenior")
                        .WithMany()
                        .HasForeignKey("PricePerSeniorId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Segment", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.FlightSegment", "FlightSegment")
                        .WithMany()
                        .HasForeignKey("FlightSegmentId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.PricingDetail", "PricingDetailPerAdult")
                        .WithMany()
                        .HasForeignKey("PricingDetailPerAdultId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.PricingDetail", "PricingDetailPerChild")
                        .WithMany()
                        .HasForeignKey("PricingDetailPerChildId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.PricingDetail", "PricingDetailPerInfant")
                        .WithMany()
                        .HasForeignKey("PricingDetailPerInfantId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.PricingDetail", "PricingDetailPerSenior")
                        .WithMany()
                        .HasForeignKey("PricingDetailPerSeniorId");

                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.Service", "Service")
                        .WithMany("Segments")
                        .HasForeignKey("ServiceId");
                });

            modelBuilder.Entity("Jasarsoft.AmadeusDev.Data.Flights.Service", b =>
                {
                    b.HasOne("Jasarsoft.AmadeusDev.Data.Flights.OfferItem", "OfferItem")
                        .WithMany("Services")
                        .HasForeignKey("OfferItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
